### ISSUE TITLE
Support for useFakeTimers('modern')

### ISSUE THREAD

**Issue by mgmolisani** [freshollie/jest-dynalite#18]
I would like to be able to use this lib to mock out dynamo but am reaching a blocking issue when using jest v26 features, namely `useFakeTimers('modern')`.

Using the preset, any test that calls into the local db results in the following error:
```
TypeError: Cannot read property 'useFakeTimers' of undefined
...
jest.useFakeTimers(`modern`);
     ^
```

I attempted to patch in the calls to `useFakeTimers` to accept the `"modern"` type argument, but that did not change the outcome. Any test that does not include the call to the db works as expected. I am fairly new to using jest so I'm not counting out user error, but it seems like something is off only when this lib is involved in the test. Worth noting, this will become the default in the next major version of jest.

**Comment by freshollie** [comment]
Hey! Thanks for raising this.

Could you provide some more context to your example? Would be helpful for me to diagnose.

Looking at the error you provide, I don't really understand what's going on because `jest` should never become undefined.

**Comment by mgmolisani** [comment]
Sure. Here is basically the testing I was able to do to see where tests failed to run. It did not matter where I set jest timers to `'modern'`. `timers: 'modern'` in config, `beforeAll`, `beforeEach`, in the test body, all failed similarly.

```
describe(`test`, () => {
  it(`uses dynalite and modern timers`, async () => {
    jest.useFakeTimers(`modern`)
    // ^ This fails with that extremely weird error suggesting jest is undefined
    await someFunctionThatUsesTheDb()
  })
  it(`uses dynalite and legacy timers`, async () => {
    jest.useFakeTimers()
    // ^ This works but doesn't provide new APIs and will not be the default in jest v27
    await someFunctionThatUsesTheDb()
  })
  it(`doesnt use dynalite `, async () => {
    jest.useFakeTimers(`modern`)
    // ^ This works fine
    await someFunctionThatDoesntUseTheDb()
  })
})
```

**Comment by freshollie** [comment]
@mgmolisani I have put in a PR to fix this if you can take a look (I've added a test case based off your example).

Just a note, running `useFakeTimers("modern")` and then `useFakeTimers()` will actually cause real issues, you have to reset fake timers before switching to the legacy timers, I'm not sure if that's what you intended in your example.

**Comment by mgmolisani** [comment]
> @mgmolisani I have put in a PR to fix this if you can take a look (I've added a test case based off your example).
> 
> Just a note, running `useFakeTimers("modern")` and then `useFakeTimers()` will actually cause real issues, you have to reset fake timers before switching to the legacy timers, I'm not sure if that's what you intended in your example.

Great, I will take a look at it shortly. The example was not a real one and I did not attempt to run each of those tests in the same env. I only wrote them that way for brevity. Consider each one to have been run as an independent check.

**Comment by freshollie** [comment]
Great, there is actually something wrong with the PR so need to make some fixes anyway.

**Comment by freshollie** [comment]
Release as `v3.2.2`

**Comment by scottybrown** [comment]
Just what I needed, thanks!

**Comment by freshollie** [comment]
@scottybrown if you wanna use this you might actually need to use `3.2.3` as there was a bug in `3.2.2`
