### ISSUE TITLE
AWS SDK v3

### ISSUE THREAD

**Issue by eryon** [freshollie/jest-dynalite#26]
Now that v3 has been [finalized and released](https://aws.amazon.com/blogs/developer/modular-aws-sdk-for-javascript-is-now-generally-available/), is there a plan in the works to introduce an update to `jest-dynalite` to support it?

**Comment by freshollie** [comment]
Hey! Are there any specific features which v3 adds which you'd be looking for? Or is it more to use the v3 SDK when installed as a peer dependency instead of the old SDK?

**Comment by eryon** [comment]
@freshollie we migrated to v3 for the modularity and middleware changes, so no need for anything new from jest-dynalite... just the support for it! In the meantime, we've switched to the Docker [amazon/dynamodb-local](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.html) image but it's more setup and annoying that using dynalite :)

**Comment by freshollie** [comment]
That's fine. As a work around for now, did you try and keep `aws-sdk@2` installed? What happened if you did attempt this?

**Comment by eryon** [comment]
I did try that (moved v2 to a devDep), and it looks promising but doesn't fully work. Tests that try to get into the db fail with `ECONNREFUSED`:
```
Error: connect ECONNREFUSED 127.0.0.1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)
```

**jest.config.js**
```js
module.exports = {
  basePort: 8000,
  tables: [
    {
      TableName: 'testState',
      KeySchema: [
        {
          AttributeName: 'snapshot',
          KeyType: 'HASH'
        },
        {
          AttributeName: 'timestamp',
          KeyType: 'RANGE'
        }
      ],
      AttributeDefinitions: [
        {
          AttributeName: 'snapshot',
          AttributeType: 'S'
        },
        {
          AttributeName: 'timestamp',
          AttributeType: 'N'
        }
      ],
      ProvisionedThroughput: {
        ReadCapacityUnits: 1,
        WriteCapacityUnits: 1
      }
    }
  ]
};
```

And here's my factory fn for the client (no `config` given in tests)
```js
function buildDocumentClient(config = {}) {
  const client = new DynamoDBClient({
    endpoint: 'https://dynamodb.us-west-2.amazonaws.com',
    ...(process.env.MOCK_DYNAMODB_ENDPOINT  && {
      credentials: {
        accessKeyId: 'dummytest',
        secretAccessKey: 'dummytest'
      },
      endpoint: process.env.MOCK_DYNAMODB_ENDPOINT ,
      region: 'local',
      tls: false
    }),
    ...config
  });
```

**Comment by freshollie** [comment]
Hmm, looks like its trying to connect via `:80` instead of the port provided via `endpoint: process.env.MOCK_DYNAMODB_ENDPOINT`. 

Firstly, are you sure your `...config` is not overriding the `endpoint`?

Secondly, can you try `endpoint: {hostname: process.env.MOCK_DYNAMODB_ENDPOINT.split(':')[0], port: process.env.MOCK_DYNAMODB_ENDPOINT.split(':')[1] }`

**Comment by eryon** [comment]
`config` is definitely not used for these tests. Setting the endpoint directly creates a new and more interesting error:
```
Error: write EPROTO 140132395091840:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)
```

I played with it a little more and we need the protocol now, too, so I set the endpoint using 
```js
endpoint: `http://${process.env.MOCK_DYNAMODB_ENDPOINT}`
```

However this also errors:
```
ResourceInUseException: ResourceInUseException
    at deserializeAws_json1_0CreateTableCommandError (/home/<snip>/node_modules/@aws-sdk/client-dynamodb/protocols/Aws_json1_0.ts:1490:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by freshollie** [comment]
Are you recreating a table which already exists? https://docs.aws.amazon.com/aws-sdk-php/v2/api/class-Aws.DynamoDb.Exception.ResourceInUseException.html

**Comment by eryon** [comment]
> 
> 
> Are you recreating a table which already exists? https://docs.aws.amazon.com/aws-sdk-php/v2/api/class-Aws.DynamoDb.Exception.ResourceInUseException.html

Yup, I was doing that as part of my dynamodb-local work and I forgot to remove that for this re-check we've been doing. Once I stop that, it's working fine and tests are passing once more w/jest-dynalite on AWS v2 and the rest of the app code on AWS v3.

**Comment by freshollie** [comment]
Great! Thanks for testing, I'll get something out so that you don't have to do this manual work around and so you don't need to keep the old `aws-sdk` installed.

**Comment by eryon** [comment]
Thanks too, you're welcome!

**Comment by freshollie** [comment]
@eryon I've opened a PR for this, might be worth checking out my recommendations in the README

**Comment by eryon** [comment]
Awesome, and good to know. I'll keep an eye out for the release 🎉

**Comment by freshollie** [comment]
Releasing as `v3.3.0`. Can you give it a go?

**Comment by eryon** [comment]
> Releasing as `v3.3.0`. Can you give it a go?

Works like a charm, thanks!
