### ISSUE TITLE
Since new `v3.3.0`, started to receive the `Cannot find module '@aws-sdk/client-dynamodb'` error

### ISSUE THREAD

**Issue by doitadrian** [freshollie/jest-dynalite#30]
Since the new version was released, we started receiving this error in our CI:

![image](https://user-images.githubusercontent.com/5121148/103893183-27cab780-50ed-11eb-8ea9-f24bfba0d069.png)

Anybody else having this issue?

**Comment by corollari** [comment]
This problem was caused because #28 added the @aws-sdk/client-dynamodb package as a peerDepedency (see [this](https://github.com/freshollie/jest-dynalite/blob/b827c75a5ba72b38f8abebe62b7af6ab7323fa81/package.json#L47)). 

@freshollie What do you think about releasing the new version as 4.0.0? This way it won't break current systems

**Comment by corollari** [comment]
@doitadrian A work-around for this problem can be to just pin the version of jest-dynalite to 3.2.5

**Comment by freshollie** [comment]
This was designed not to be a breaking change, but I forgot that I should have used dynamic imports to import the correct dynalite version. Will try and get a fix our now.

**Comment by freshollie** [comment]
Fixed in https://github.com/freshollie/jest-dynalite/commit/56e3e43003ad8d46de70076f4949b8971e42a749

**Comment by freshollie** [comment]
Will release as `v3.3.1` shortly.

**Comment by freshollie** [comment]
Also @doitadrian are you not using a lockfile in your CI? Because I would not have expected `jest-dynalite` to be using the latest version unless explicitly specified.

**Comment by freshollie** [comment]
@corollari just to clarify, `@aws-sdk/client-dynamodb` is an optional peer dependency. You are free to use `aws-sdk` or `@aws/client-dynamodb`. Please install which ever works best for you.

**Comment by freshollie** [comment]
Published. Let me know if this fixes your CI (without downgrading)

**Comment by doitadrian** [comment]
I did hardcode the version to `3.2.5` immediately after I experienced this issue, so I kinda resolved it on my end.

But yes, will try reverting the change, and let you know if everything is fine (tomorrow).

Thank you @freshollie for your patience and time! 🍻

**Comment by doitadrian** [comment]
Sorry for the delay, but just wanted to let you know that this works.

Thanks a lot guys, you rock! 🚀  🚀 

Closing the issue.
