### ISSUE TITLE
Does this library support concurrent testing?

### ISSUE THREAD

**Issue by napsta32** [freshollie/jest-dynalite#33]
I want to test multiple concurrent operations (update, put, delete...) in dynamodb and I am wondering if this library will handle it in parallel or not. I want to test my conditional writes.

I understand that real dynamodb engine can have issues because engine needs to write into multiple nodes, and some can get outdated.

**Comment by freshollie** [comment]
I have used `jest-dynalite` to test my concurrent updates (where I want dynamodb to use the condition expression), and it seems to work fine by just doing an `await Promise.all([update1(), update2()])`.

Let me know how you get on.
