### ISSUE TITLE
Getting "ReadError: Database is not open" every time a test fails

### ISSUE THREAD

**Issue by KevinVR** [freshollie/jest-dynalite#34]
Whenever an `expect` clause fails, I get the `ReadError: Database is not open` error.

Fixing the expect to be successful fixes it. However, this makes it hard to find which `expect` is failing.

For example:
```
expect(response.status).toEqual(400);
Run:
ReadError: Database is not open
    at /Users/a/Documents/Projects/CMT/web/node_modules/levelup/lib/levelup.js:190:15
    at /Users/a/Documents/Projects/CMT/web/node_modules/encoding-down/index.js:75:21
    at processTicksAndRejections (node:internal/process/task_queues:80:21)
```

After fix:

```
expect(response.status).toEqual(200);
Run:
No errors / test complete fine
```

But the actual expect errors aren't shown, so I can't know which one is actually failing.

Running on node v15.9.0

Could this be due to a wrong setup?

Jest config:
```
export default {
  clearMocks: true,
  coverageDirectory: "coverage",
  coverageProvider: "v8",
  preset: "jest-dynalite",
  "roots": [
    "<rootDir>/src"
  ],
  "testMatch": [
    "**/__tests__/**/*\.test\..+(ts|tsx|js)",
    "**/?(*.)+(spec|test).+(ts|tsx|js)"
  ],
  "transform": {
    "^.+\\.(ts|tsx)$": "ts-jest"
  }
};

```

Jest dynalite config doesn't have anything special, and it does work, as long as the expect doesn't fail.

**Comment by freshollie** [comment]
Could you provide more context as to what your code is doing? You'll get an error like this if you have a query which is executing after the database has closed. Are you able to make a simple reproduction?

**Comment by freshollie** [comment]
Hey @KevinVR I'd love to assist you here, but if you don't follow up soon I'm going to close this :/

**Comment by KevinVR** [comment]
Thanks for the answer @freshollie! Sorry for the delay. I will close this ticket now, once I have an example setup I'll re-open!
