### ISSUE TITLE
documentClient.transactWrite isn't supported

### ISSUE THREAD

**Issue by jsphweid** [freshollie/jest-dynalite#35]
Test fails with ```Failed: [UnknownOperationException: null]```

It looks like at one time [dynamodb local didn't support](https://stackoverflow.com/a/56709065/4918389) `transactWrite` but I think it might now... My tests passed when I used the [other lib](https://github.com/shelfio/jest-dynamodb) (that uses java dynamodb)

Reproducible by modifying the e2e tests slightly:
![image](https://user-images.githubusercontent.com/8868585/111877808-0dc21680-8973-11eb-8fc6-eefa718cc038.png)

**Comment by jsphweid** [comment]
More R&D, it appears to be [an issue](https://github.com/mhart/dynalite/issues/98) with `dynalite`

**Comment by freshollie** [comment]
Yep :( #27

**Comment by jsphweid** [comment]
Dang, sorry I missed the duplicate...
