### ISSUE TITLE
Writing jest-dynalite-config in TypeScript

### ISSUE THREAD

**Issue by DragosRotaru** [freshollie/jest-dynalite#52]
Hi, I would like to use the mock data functions I have in my typescript codebase for the dynalite config. Is there any way to do this?

**Comment by freshollie** [comment]
Hey! I'll look into this. It's possible that if I allow the config to be `.ts` then this will work, as under the hood I'm just using `require` to resolve the config file. I guess if `ts-jest` is transpiling anything from `require` this may work.

**Comment by freshollie** [comment]
I've created a PR for this, would be great if you could give it a once over and then I'll publish and you can have a test?

**Comment by freshollie** [comment]
@DragosRotaru looking for any feedback here. Is this what you are looking for?

**Comment by DragosRotaru** [comment]
@freshollie Thanks Ollie! I left 2 comments

**Comment by freshollie** [comment]
This has been published under `v3.4.0`
