### ISSUE TITLE
setImmediate is not defined

### ISSUE THREAD

**Issue by revmischa** [freshollie/jest-dynalite#54]
```
  ● Test suite failed to run

    ReferenceError: setImmediate is not defined

      at Object.<anonymous> (node_modules/memdown/immediate.js:1:100)
      at Object.<anonymous> (node_modules/memdown/memdown.js:10:20)
      at Object.<anonymous> (node_modules/dynalite/db/index.js:6:15)
      at Object.<anonymous> (node_modules/dynalite/validations/index.js:2:10)
      at Object.<anonymous> (node_modules/dynalite/index.js:8:19)
      at Object.<anonymous> (node_modules/jest-dynalite/src/db.ts:1:1)
      at Object.<anonymous> (node_modules/jest-dynalite/src/setupTables.ts:1:1)
      at Object.<anonymous> (node_modules/jest-dynalite/setupTables.js:1:83)
```

**Comment by freshollie** [comment]
What version of node is this?

**Comment by revmischa** [comment]
`v14.15.4`

**Comment by freshollie** [comment]
Very weird. `setImmediate` is definitely part of node API: https://nodejs.org/api/timers.html#timers_setimmediate_callback_args

**Comment by revmischa** [comment]
Maybe it's `testEnvironment` in my jest config?
```
module.exports = {
  moduleFileExtensions: ["ts", "tsx", "js"],
  moduleNameMapper: {
    // Mocks out all these file formats when tests are run
    "\\.(css|less|scss|sass)$": "identity-obj-proxy",
    "\\.(jpg|ico|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "identity-obj-proxy",
  },
  roots: ["./packages"],
  preset: "jest-dynalite",
  globals: {
    "ts-jest": {
      tsconfig: "tsconfig.json",
    },
  },
  testEnvironment: "jsdom",
  setupFilesAfterEnv: ["jest-canvas-mock"],

  testMatch: ["**/__tests__/**/*.+(ts|tsx)", "**/?(*.)+(spec|test).+(ts|tsx)"],
  // transform: {
  // "^.+\\.tsx?$": "ts-jest",
  // "^.+\\.tsx$": "babel-jest",
  // },
  transformIgnorePatterns: ["[/\\\\]node_modules[/\\\\].+\\.(js|jsx|mjs|ts|tsx)$"],
  collectCoverageFrom: ["**/*.{ts,tsx}", "!**/node_modules/**", "!**/vendor/**"],
  projects: ["<rootDir>", "<rootDir>/packages/*"],
}
```

**Comment by freshollie** [comment]
Tried this and I can't reproduce locally

**Comment by revmischa** [comment]
removing `testEnvironment: "jsdom"` fixed it
But now I have a problem that I'm in a monorepo that requires some tests to be run in jsdom and some in node environments :(
This is more of a jest issue but if I try overriding the testEnvironment and setting it to `jsdom` in a frontend package, the package still tries to load the `jest-dynalite` preset and gives me the original error.

It would be nice to just have jest-dynalite enabled on certain (node) packages and not the frontend packages in my monorepo. Is that somehow possible?

**Comment by revmischa** [comment]
I ended up using https://jestjs.io/docs/configuration#projects-arraystring--projectconfig here

**Comment by freshollie** [comment]
Nice. Btw, you shouldn't be using the preset if you are using a custom `testEnvironment`

It's noted in the docs already: https://github.com/freshollie/jest-dynalite#simple-usage-preset

You should use the Advanced setup: https://github.com/freshollie/jest-dynalite#advanced-setup
