### ISSUE TITLE
DescribeTable returns ItemCount equal to 0. 

### ISSUE THREAD

**Issue by ebisbe** [freshollie/jest-dynalite#74]
I'm wanting to get the ItemCount from a table and I need to use DescribeTable. The value I always get is 0 despite adding items. Is that the expected behaviour?

**Comment by freshollie** [comment]
Interesting, can I see the code you are executing?

**Comment by ebisbe** [comment]
Yeah, sure. It's working fine on a real call to DynamoDB.

```

let ddb
const getDynamo = (loadCredentials = false) => {
  if (ddb) return ddb

  updateCredentials(loadCredentials)

  const config = {
    maxRetries: 3,
    convertEmptyValues: true,
    ...(process.env.MOCK_DYNAMODB_ENDPOINT && {
      endpoint: process.env.MOCK_DYNAMODB_ENDPOINT,
      sslEnabled: false,
      region: "local"
    })
  }
  ddb = new AWS.DynamoDB(config)
  return ddb
}

const dynamodb = AwsUtils.getDynamo()
 const { Table: tagsTable } = await dynamodb
      .describeTable({ TableName: group_tags_table })
      .promise()
```
I'm filling with a `writeBatch()` call on the test.

**Comment by freshollie** [comment]
So `describeTable` doesn't return the item count? :/

Would likely be a limitation of `dynalite`

**Comment by ebisbe** [comment]
> So `describeTable` doesn't return the item count? :/
> 
> Would likely be a limitation of `dynalite`

Nope. I was searching what used under the hood and thought that `dynalite` was just a fancy name... I'll ask there

**Comment by Noorts** [comment]
Note: This issue still appears to remain unsolved by dynalite: https://github.com/mhart/dynalite/issues/102
