### ISSUE TITLE
babel-jest 28 & jest 28: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by vincent-ogury** [freshollie/jest-dynalite#82]
I've upgrade babel-jest and jest to version 28.

```
-    "babel-jest": "^27.3.1",
+    "babel-jest": "^28.0.2",
-    "jest": "^27.3.1",
+    "jest": "^28.0.2",
     "jest-dynalite": "^3.4.4",
```

I've got this error with jest-dynalite now:

```
    TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

      at ../node_modules/jest-dynalite/dist/config.js:23:29
          at Array.find (<anonymous>)
      at findConfigOrError (../node_modules/jest-dynalite/dist/config.js:22:79)
      at Object.setConfigDir (../node_modules/jest-dynalite/dist/config.js:47:5)
      at Object.exports.default (../node_modules/jest-dynalite/dist/setup.js:5:14)
      at new DynaliteEnvironment (../node_modules/jest-dynalite/dist/environment.js:17:28)
```

**Comment by freshollie** [comment]
Hmm, I wonder if `jest@28` doesn't provide `rootDir` on the project config:

https://github.com/freshollie/jest-dynalite/blob/master/src/environment.ts#L13

Thanks for the report, will look into it when I can. Feel free to submit a PR if you can work this out

**Comment by freshollie** [comment]
Verified. Not sure why it's not listed, but jest 28 does break some stuff. I've updated to jest 28, and ensured backwards compatibility with an e2e test against jest 27. Will be published as `v3.5.1` later today

**Comment by vincent-ogury** [comment]
Great !. I'm gonna test this right away. thanks.

**Comment by freshollie** [comment]
This fix should be out. Feel free to reopen if this doesn't work for you

**Comment by vincent-ogury** [comment]
I'm update jest+babel-jest + jest-dynalite
After few readjustment, all works.

Thanks a lot.

**Comment by freshollie** [comment]
What were the re-adjustments?
