### ISSUE TITLE
Unable to run tests - Server timeout

### ISSUE THREAD

**Issue by napsta32** [freshollie/jest-dynalite#9]
I was trying to migrate from jest-dynamodb to dynalite but weird timeout error started appearing. I used exact same configuration from jest-dynamodb, I only updated config file name and preset. I also tried increasing jest timeout.

jest-dynalite: 3.0.0
collectCoverage: true
OS: Ubuntu 16.04LTS

Coverage report is working fine.

```
 FAIL  test/my-test.test.js (68.543 s)
  ✕ my test (60027 ms)

  ● my test

    Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:27:45)

  ● my test

    NetworkingError: connect ECONNREFUSED 127.0.0.1:8001Error: connect ECONNREFUSED 127.0.0.1:8001



  ● my test

    Timeout - Async callback was not invoked within the 60000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 60000 ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:27:45)

(node:29000) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:8001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
(node:29000) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:29000) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by corollari** [comment]
Could you post a minimal test case with that behavior?

**Comment by napsta32** [comment]
I was trying a minimal test without using database. not sure if it would help

**Comment by corollari** [comment]
I'm not sure I follow, could you post the code that triggered the errors on your first post?

**Comment by napsta32** [comment]
I just created a minimal test and it is failing with same errors. I also see that MOCK_DYNAMODB_ENDPOINT is not set.

```
import AWS from 'aws-sdk';

test('put database', async () => {
    jest.setTimeout(10000);

    const config = true ? {
        endpoint: process.env.MOCK_DYNAMODB_ENDPOINT,
        sslEnabled: false,
        region: "local"
    } : {};
    console.log(config);
    let dynamoDB = new AWS.DynamoDB.DocumentClient(config);

    await dynamoDB.put({
        TableName: 'bad-test',
        Item: {phone: 123},
        ConditionExpression: `#pid <> :partitionKey`,
        ExpressionAttributeNames: {
            '#pid': 'phone',
        },
        ExpressionAttributeValues: {
            ':partitionKey': '123',
        }
    }).promise();
});

```

**Comment by corollari** [comment]
I tried to reproduce your error in a repo but couldn't, could you check [this](https://github.com/corollari/test-jest-dynalite) and compare that environment to your own? Are there any differences to the configuration files? If you change yoru configuration files to the ones on my repo does it work for you?

>  I also see that MOCK_DYNAMODB_ENDPOINT is not set.

That seems to be the cause of the problem, maybe jest is not properly picking up the preset? If that was the case I'd expect the whole thing to fail instead of getting a timeout tho, well let's see if we can reproduce your problem first.

**Comment by napsta32** [comment]
It is related to the jest.config.js file. I erased my whole configuration and replaced it with preset only.

**Comment by napsta32** [comment]
Found it. I just had to remove `testEnvironment: "node",` from jest.config.js.

**Comment by napsta32** [comment]
looks like I skipped `advanced setup` section and this was added when I initialized jest config file.
Thanks for the support anyways!

**Comment by corollari** [comment]
Great, I've created a PR to improve the documentation on that part.

**Comment by KevinVR** [comment]
This is a great! I also had the same issue with `testEnvironment: 'node'` which I left as part of the default jest config file. Removing it fixed it!
