### ISSUE TITLE
Support for ReturnValuesOnConditionCheckFailure

### ISSUE THREAD

**Issue by vincent-ogury** [freshollie/jest-dynalite#93]
Hi,

Can you add support of ReturnValuesOnConditionCheckFailure parameters in putItem,updateItem,batchWriteItem ...

https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_ConditionCheck.html

When the API thrown an error with code = 'ConditionalCheckFailedException'
Then the err include an "Item" containing the document in the db:

```
const cli = new AWS.DynamoDB({region:'local', endpoint: process.env.MOCK_DYNAMODB_ENDPOINT})
try {
  await cli.putItem({TableName: 'X', Item: {_id:{S:'test'}, v:{N:"1"}}}).promise()
  await cli.putItem({TableName: 'X', Item: {_id:{S:'test'}, v:{N:"3"}}
    ReturnValuesOnConditionCheckFailure: 'OLD_OLD',
    ExpressionAttributeNames: {'#V' : 'v'},
    ConditionExpression: '#V = :V',
    ExpressionAttributeValues: {':V':{N:"2}}
  }).promise()
} catch (err) {
  console.debug(err.code, err.Item)
  // Item = { _id : {S: "test"}, v: {N: "1}}
}
```

It works when I use the real dynamodb directly, and failed with this module or the dynamodb local provided by amazon.
this feature were release in july this year.

Thanks

**Comment by freshollie** [comment]
Hey! Unfortunately this relates to the upstream package ([dynalite](https://github.com/architect/dynalite))

Consider making this issue over there

**Comment by vincent-ogury** [comment]
ok thx. will do

**Comment by vincent-ogury** [comment]
If dynalite support this, does it mean it will works on this module automatically ?

**Comment by freshollie** [comment]
Yes. This library just starts up the dynalite instance for each test runner :)

**Comment by vincent-ogury** [comment]
ok thx. I guess it pull the last version all the time ?
I will close this one then

**Comment by freshollie** [comment]
No, it doesn’t always pull the latest version but the library has not been updated in a while.
